# Basic site settings
title: "Rakesh's Embedded Systems Projects"
description: "Exploring embedded systems, from robust, low-power designs to AI integration."
author: "Rakesh Menon"
baseurl: "" # Leave blank for the root site
url: "https://<your-username>.github.io" # Replace with your GitHub Pages URL
theme: jekyll-theme-cayman # Chosen theme; change if you prefer a different one
# Navigation bar links
# Add new pages as needed (e.g., about.md, projects.md)
nav_links:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"

# Social links
# Add your social media or GitHub profile links
social_links:
  github: "https://github.com/rake218"
  linkedin: "https://www.linkedin.com/in/rakeshmenon2202/"
